image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest

Build container:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY_IMAGE
  stage: build
  tags:
    - docker
  script:
    - docker build -f Dockerfile.build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

Test:
  image: $CONTAINER_TEST_IMAGE
  variables:
    # By default gitlab-runner will clone code from my repo into directory /builds/Domnyk/hadrian/
    # Setting GIT_STRATEGY to none prevents it
    GIT_STRATEGY: none
    MIX_ENV: test
    POSTGRES_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "postgres"  
    POSTGRES_DB: hadrian_prod  
  stage: test
  services:
    - postgres:latest
  before_script:
    # cd is necessary: by default gitlab-runner is launched in /builds/Domnyk/hadrian
    - cd /hadrian
  script:
    - mix ecto.create
    - mix ecto.migrate
    - mix test

