image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
# 
# variables:
#   POSTGRES_HOST: postgres
#   POSTGRES_USER: postgres
#   POSTGRES_PASSWORD: "postgres"
#
variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest

Build container:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY_IMAGE
  stage: build
  tags:
    - docker
  script:
    - docker build -f Dockerfile.build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

Test:
  image: $CONTAINER_TEST_IMAGE
  variables:
    GIT_STRATEGY: none
    MIX_ENV: test
    POSTGRES_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "postgres"  
    POSTGRES_DB: hadrian_prod  
  stage: test
  services:
    - postgres:latest
  before_script:
    - cd /hadrian
#     - apk --update add postgresql-client
#     - mix local.hex --force
#     - mix local.rebar --force
#     - mix deps.get --only $MIX_ENV
  script:
    - mix ecto.create
    - mix ecto.migrate
    - mix test

