image: bitwalker/alpine-elixir-phoenix:1.6.6

stages:
  - build
  - test
  - release

variables:
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"  

Build:
  stage: build
  services:
    - postgres:latest
  variables:
    MIX_ENV: dev
    POSTGRES_DB: hadrian_dev
  before_script:
    - npm install -g brunch
    - cd ./assets && npm install && cd ..
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get --only $MIX_ENV
    - mix ecto.create
    - mix ecto.migrate
  script:
    - cd ./assets && brunch build
    - cd .. && mix phx.digest
    - mix compile
  
Test:
  stage: test
  services:
    - postgres:latest
  variables:
    MIX_ENV: test
    POSTGRES_DB: hadrian_test
  before_script:
    - apk --update add postgresql-client
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get --only $MIX_ENV
    - mix ecto.create
    - mix ecto.migrate
  script:
    - mix test

Release:
  stage: release
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PROJECT_NAME.git
    - git push heroku master
  
