image: docker:latest

# services:
#   - docker:dind

stages:
  - build
# 
# variables:
#   POSTGRES_HOST: postgres
#   POSTGRES_USER: postgres
#   POSTGRES_PASSWORD: "postgres"
# 
build:
  # variables:
  #  MIX_ENV: prod
  #  POSTGRES_DB: hadrian_prod
  stage: build
  tags:
    - docker
  before_script:
    - docker build -f Dockerfile.build -t ci-project-build-$CI_COMMIT_SHA .
    - docker create
      -v /build/deps
      -v /build/_build
      -v /build/rel
      -v /root/cache/rebar3/
      --name build_data_$CI_COMMIT_SHA busybox /bin/true
    #  - npm install -g brunch
    #  - cd ./assets && npm install && cd ..
    #  - mix local.hex --force
    #  - mix local.rebar --force
    #  - mix deps.get --only $MIX_ENV
    #  - mix ecto.create
    #  - mix ecto.migrate
  script:
    - docker info

# test:
#   variables:
#     MIX_ENV: test
#     POSTGRES_DB: hadrian_prod
#   stage: test
#   before_script:
#     - apk --update add postgresql-client
#     - mix local.hex --force
#     - mix local.rebar --force
#     - mix deps.get --only $MIX_ENV
#     - mix ecto.create
#     - mix ecto.migrate
#   script:
#     - mix test 

