image: docker:latest

services:
   - docker:dind

stages:
  - build
# 
# variables:
#   POSTGRES_HOST: postgres
#   POSTGRES_USER: postgres
#   POSTGRES_PASSWORD: "postgres"
# 
Build container:
  variables:
    IMAGE_NAME: ci-project-build-$CI_COMMIT_SHA
  stage: build
  tags:
    - docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY_IMAGE
    #  - npm install -g brunch
    #  - cd ./assets && npm install && cd ..
    #  - mix local.hex --force
    #  - mix local.rebar --force
    #  - mix deps.get --only $MIX_ENV
    #  - mix ecto.create
    #  - mix ecto.migrate
  script:
    - docker build -f Dockerfile.build -t $IMAGE_NAME .
    - docker push $CI_REGISTRY_IMAGE:latest

# test:
#   variables:
#     MIX_ENV: test
#     POSTGRES_DB: hadrian_prod
#   stage: test
#   before_script:
#     - apk --update add postgresql-client
#     - mix local.hex --force
#     - mix local.rebar --force
#     - mix deps.get --only $MIX_ENV
#     - mix ecto.create
#     - mix ecto.migrate
#   script:
#     - mix test 

