image: bitwalker/alpine-elixir-phoenix:1.6.6

stages:
  - deps download
  - deps compilation
  - build
  - test
  - release

variables:
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"  

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - ./deps
    - ./_build

Get dependencies for all envs:
  stage: deps download
  script:
    - mix deps.get

Compile dependencies for dev env:
  stage: deps compilation
  script:
    - MIX_ENV=dev mix deps.compile

Compile dependencies for test env:
  stage: deps compilation
  cache:
    key: "$CI_COMMIT_REF_SLUG-test"
    paths:
      - ./deps
      - ./_build 
  script:
    - MIX_ENV=test mix deps.compile

Run migrations:
  stage: build
  variables:
    MIX_ENV: dev
    POSTGRES_DB: hadrian_dev
  services:
    - postgres:latest  
  before_script:
    - mix ecto.create
  script:
    - mix ecto.migrate

Build app:
  stage: build
  variables: 
    MIX_ENV: dev
  before_script:
    - mix local.hex --force
    - mix local.rebar --force
  script:
    mix compile

Compile static assets:
  stage: build
  before_script:
    - npm install -g brunch
    - cd ./assets && npm install && cd ..
  script:
    - cd ./assets && brunch build
    - cd .. && mix phx.digest
  
Test:
  stage: test
  cache:
    key: "$CI_COMMIT_REF_SLUG-test"
    paths:
      - ./deps
      - ./_build
  services:
    - postgres:latest
  variables:
    MIX_ENV: test
    POSTGRES_DB: hadrian_test
  before_script:
    - apk --update add postgresql-client
    - mix local.hex --force
    - mix local.rebar --force
    - mix ecto.create
    - mix ecto.migrate
  script:
    - mix test

Release:
  stage: release
  cache: {}
  before_script:
    - apk --update add ruby ruby-dev 
    - gem install --no-document json
    - gem install --no-document dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_PROJECT_NAME --api-key=$HEROKU_API_KEY
  only:
    - master
  when: manual
  
