language: elixir
elixir: '1.7.2'
otp_release: '21.0'

services:
  - postgresql


stages:
  - "Build"
  - "Test"
  - name: "Release"
  - if: branch = master

jobs:
  include:
  - stage: "Build"
    name: "Build app"
    before_script:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get --only $MIX_ENV
    script: mix compile
  - stage: "Build"
    env:
      - MIX_ENV=dev POSTGRES_DB=hadrian_dev POSTGRES_USER=postgres POSTGRES_PASSWORD=""
    name: "Run migrations"
    before_script:
      - psql -c "create database $POSTGRES_DB;" -U $POSTGRES_USER
      - mix deps.get --only $MIX_ENV
      - mix ecto.create
    script:
      - mix ecto.migrate




