language: elixir
elixir: '1.7.2'
otp_release: '21.0'

services:
  - postgresql

addons:
  postgresql: "9.6"


stages:
  - "Build"
  - "Test"
  - name: "Release"
  - if: branch = master

jobs:
  include:
  - stage: "Build"
    name: "Build app"
    before_script:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get --only $MIX_ENV
    script: mix compile
  - stage: "Build"
    env:
      - MIX_ENV=dev POSTGRES_DB=hadrian_dev POSTGRES_USER=postgres POSTGRES_PASSWORD=""
    name: "Run migrations"
    before_script:
      - psql -c "create database $POSTGRES_DB;" -U $POSTGRES_USER
      - mix deps.get --only $MIX_ENV
      - mix ecto.create
    script:
      - mix ecto.migrate
  - stage: "Test"
    name: "Run unit tests"
    env:
      - MIX_ENV=test POSTGRES_DB=hadrian_test POSTGRES_USER=postgres POSTGRES_PASSWORD=""
    before_script:
    - psql -c "create database $POSTGRES_DB;" -U $POSTGRES_USER
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get --only $MIX_ENV
    - mix ecto.create
    - mix ecto.migrate
    script:
      - mix test
  - stage: "Release"
    name: "Release"
    script: skip
    deploy:
      provider: heroku
      api_key: $HEROKU_API_KEY
      app: thawing-crag-67620







